domain: avadae.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://avadae.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /game-groupprojects     # place folder name if the site is served in a subfolder
plugins:
  - jekyll-include-cache
  - jekyll-polyglot
  - jekyll-sitemap
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
title: "Student Game Projects"
title_separator: "|"
subtitle: "Create a POC with our students"
name: "Digital Arts & Entertainment"
description: "Create a proof of concept of your game ideas with our students."
repository: "avadae/game-groupprojects"
logo: "/assets/images/dae_headerlogo.webp"
defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
languages: ["en", "nl"]
default_lang: "en"
exclude_from_localization: ["docs", "assets", "_sass", "_includes"]
parallel_localization: false
atom_feed:
  hide: true
footer:
  links:
    - label: "DAE Website"
      url: "https://digitalartsandentertainment.be"
      icon: "fas fa-globe"
